const PokemonType = {
  normal: "normal",
  fighting: "fighting",
  flying: "flying",
  poison: "poison",
  ground: "ground",
  rock: "rock",
  bug: "bug",
  ghost: "ghost",
  steel: "steel",
  fire: "fire",
  water: "water",
  grass: "grass",
  electric: "electric",
  psychic: "psychic",
  ice: "ice",
  dragon: "dragon",
  dark: "dark",
  fairy: "fairy",
  none: "none",
};

const pokemonTypes = [
  PokemonType.normal,
  PokemonType.fighting,
  PokemonType.flying,
  PokemonType.poison,
  PokemonType.ground,
  PokemonType.rock,
  PokemonType.bug,
  PokemonType.ghost,
  PokemonType.steel,
  PokemonType.fire,
  PokemonType.water,
  PokemonType.grass,
  PokemonType.electric,
  PokemonType.psychic,
  PokemonType.ice,
  PokemonType.dragon,
  PokemonType.dark,
  PokemonType.fairy,
];

const typesInPokemondbOrder = [
  PokemonType.normal,
  PokemonType.fire,
  PokemonType.water,
  PokemonType.electric,
  PokemonType.grass,
  PokemonType.ice,
  PokemonType.fighting,
  PokemonType.poison,
  PokemonType.ground,
  PokemonType.flying,
  PokemonType.psychic,
  PokemonType.bug,
  PokemonType.rock,
  PokemonType.ghost,
  PokemonType.dragon,
  PokemonType.dark,
  PokemonType.steel,
  PokemonType.fairy,
];

module.exports = { PokemonType, pokemonTypes, typesInPokemondbOrder };